workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

stages:
  - build
  - test

build-job:
  stage: build
  image: eclipse-temurin:21-jdk
  tags:
    - linux
    - bas2301
  script:
    - chmod +x mvnw
    - ./mvnw package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

sast-semgrep:
  stage: test
  image: returntocorp/semgrep
  tags:
    - linux
    - bas2301
  script:
    # Добавляем сканирование текущей папки (.) и конфиг auto
    - semgrep scan --config auto --sarif --output report.sarif .
  artifacts:
    reports:
      sast: report.sarif
    paths:
      - report.sarif
    expire_in: 1 week