name: Secure Build Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # сборка
      - name: Build with Maven
        run: |
          chmod +x mvnw
          ./mvnw package -DskipTests

      # SAST (пз 3)
      - name: Semgrep SAST scan
        run: |
          docker run --rm -v $(pwd):/src returntocorp/semgrep semgrep scan --config auto --sarif --output report.sarif

      - name: Upload SAST report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif

      # SCA (пз 4)
      - name: Dependency Check SCA
        run: |
          ./mvnw dependency-check:check

      - name: Upload SCA Report
        uses: actions/upload-artifact@v4
        with:
          name: sca-report
          path: target/dependency-check-report.html

      # Сохранение JAR (пз 2)
      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar